---
permalink: online-help-96-97/concept_roles_delete.html
sidebar: sidebar
keywords: system, manager, create, manage, role, online, help, svm, edit
summary: "You can use System Manager to create and manage roles."
---
= Roles
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to create and manage roles.

== Add roles

You can use System Manager to add an access-control role and to specify the command or command directory that the users of the role can access. You can also control the level of access the role has to the command or command directory, and you can specify a query that applies to the command or command directory.

.Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *SVM User Details* pane, click *Roles*.
. Click *Add*.
. In the *Add Role* dialog box, specify the role name, and then add the role attributes.
. Click *Add*.

== Edit roles

You can use System Manager to modify the access of an access-control roleto a command or command directory and to restrict a user's access to only a specified set of commands.

.Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *SVM User Details* pane, click *Roles*.
. Select the role that you want to modify, and then click *Edit*.
. Modify the role attributes, and then click *Modify*.

== Roles window

You can use the Roles window to manage the roles that are associated with user accounts.

=== Command buttons

* *Add*
+
Opens the Add Role dialog box, which enables you to create an access-control role and specify the command or command directory that the role's users can access.

* *Edit*
+
Opens the Edit Role dialog box, which enables you to add or modify role attributes.

* *Refresh*
+
Updates the information in the window.

=== Roles list

The roles list provides a list of roles that are available to be assigned to users.

=== Role Attributes area

The details area displays the role attributes, such as the command or command directory that the selected role can access, the access level, and the query that applies to the command or command directory.

*Related information*

https://docs.netapp.com/us-en/ontap/authentication/index.html[Administrator authentication and RBAC^]

// 2021-12-21, Created by Aoife, sm-classic rework
