---
permalink: online-help-96-97/task_editing_local_windows_user_properties.html
sidebar: sidebar
keywords: edit, local, window, user, properties, system, manager, online, help
summary: "You can use System Manager to modify a local Windows user account if you want to change an existing user’s full name or description, or if you want to enable or disable the user account. You can also modify the group memberships that are assigned to the user account."
---
= Edit local Windows user properties with System Manager - ONTAP 9.7 and earlier
:icons: font
:imagesdir: ../media/

[.lead]
You can use ONTAP System Manager classic (available in ONTAP 9.7 and earlier) to modify a local Windows user account if you want to change an existing user's full name or description, or if you want to enable or disable the user account. You can also modify the group memberships that are assigned to the user account.

.Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *Host Users and Groups* pane, click *Windows*.
. In the *Users* tab, click *Edit*.
. In the *Modify User* window, make the required changes.
. Click *Modify*.

.Results

The attributes of the local Windows user account are modified and are displayed in the *Users* tab.

*Related information*

xref:reference_windows_window.adoc[Windows window]
