---
permalink: fc-config-esxi/index.html
sidebar: sidebar
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, hba, esx, host, computer,
summary: "Using the ONTAP System Manager classic interface (ONTAP 9.7 and earlier), you can quickly set up the FC service on a storage virtual machine (SVM), provision a LUN, and make the LUN available as a datastore using an FC HBA on an ESX host computer."
---
= FC configuration for ESXi using VSC overview
:icons: font
:imagesdir: ../media/

[.lead]
Using the ONTAP System Manager classic interface (ONTAP 9.7 and earlier), you can quickly set up the FC service on a storage virtual machine (SVM), provision a LUN, and make the LUN available as a datastore using an FC HBA on an ESX host computer.

Use this procedure if:

* You are using a supported version of Virtual Storage Console for VMware vSphere to configure storage settings for your ESX host and to provision the datastores.
* Your network uses IPv4 addressing.
* You are using traditional FC HBAs on ESXi 5.x and traditional FC switches.
+
This procedure does not cover FCoE.

* You have at least two FC target ports available on each node in the cluster.
+
Onboard FC and UTA2 (also called "`CNA`") ports, as well as some adapters are configurable. Configuring those ports is done in the ONTAP CLI and is not covered in this procedure.

* You are not configuring FC SAN boot.
* You are creating datastores on the host.
+
This procedure does not cover raw device mapping (RDM) disks or using N-port ID virtualization (NPIV) to provide FC directly to VMs.

== Other ways to do this in ONTAP
[cols=2,options="header"]
|===
| To perform these tasks with... | See this content...
| The redesigned System Manager (available with ONTAP 9.7 and later) | link:https://docs.netapp.com/us-en/ontap/task_san_provision_vmware.html[Provision SAN storage for VMware datastores^]
| The ONTAP command line interface (CLI) | link:https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html[LUN setup workflow with the CLI^]
|===

== Additional resources

If these assumptions are not correct for your situation, you should see the following resources:

* https://docs.netapp.com/us-en/ontap/san-admin/index.html[ONTAP 9 SAN administration^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html[ONTAP 9 SAN configuration^]
* https://docs.netapp.com/vapp-96/topic/com.netapp.doc.vsc-iag/home.html[Appliance administration^]
* _VMware vSphere Storage_ for your version of ESXi 5 (available from link:http://www.vmware.com[VMware^])

// 2022-01-11, BURT 1449742
